[project]
name = "to-feature-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hopsworks>=4.1.4",
    "loguru>=0.7.3",
    "pyarrow>=18.1.0",
    "pydantic-settings>=2.6.1",
    "quixstreams>=3.5.0",
]
