[project]
name = "candles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "pydantic-settings>=2.6.1",
    "quixstreams>=3.5.0",
]
