
########################################
## LLM specific things
########################################

# Sanity checking each of the LLMs
run-claude:
	uv run python -m llms.claude

run-ollama:
	uv run python -m llms.ollama



#########################################
## Local run 
#########################################
run-dev:
	uv run python run.py